import Head from "next/head";
import { Inter } from "next/font/google";
import ZoekContainer from "@/components/ZoekContainer.jsx";
import Navigation from "@/components/navigation.jsx";
import Korting from "@/components/korting.jsx";
import {useState} from "react";
import useNetwork from "@/data/network.js";
import NearbyFav from "@/components/nearby_fav";
import Stations from "@/components/stations";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
      const { network, isLoading, isError } = useNetwork()

      if (isLoading) return <div>Loading...</div>
      if (isError) return <div>Error</div>

      const stations = network.stations;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <ZoekContainer />
        <Korting />
        <Navigation />
        <NearbyFav />
        <Stations straatnaam="Ellerman 19" afstand="15" fietsen="11" slots="25"/>
        <Stations straatnaam="Ellerman 19" afstand="15" fietsen="11" slots="25"/>
        <Stations straatnaam="Ellerman 19" afstand="15" fietsen="11" slots="25"/>
        <div>
          {stations.map(station => <p key={station.id}>{station.name}</p>)}
        </div>
      </main>

      


    
    </>
  );
}
